@startuml "Deployment app"

left to right direction

actor "User" as User

usecase "Deploy Project" as Deploy
usecase "Projects" as Projects

usecase "Configure Environments" as Configuration

usecase "Run Tests Unit" as TestsUnit
usecase "Build Application" as BuildApplication
usecase "Deploy to Production" as DeployProduction

usecase "Create project" as CreateProject
usecase "Modify project" as ModifyProject
usecase "Delete project" as DeleteProject

usecase "Create domains" as CreateDomain
usecase "Modify domains" as ModifyDomain
usecase "Delete domains" as DeleteDomain

usecase "Manage environments variables" as ManageEnvVariables
usecase "Manage domains" as ManageDomains
usecase "Integrate Webhooks (automated deployment)" as IntegrateWebHooks
usecase "Notify Team on Deployment" as NotifyTeam
usecase "Generate Deployment Reports" as DeploymentReports

User --> Deploy
User --> Configuration
User --> Projects

Projects --> Deploy

Projects --> CreateProject
Projects --> ModifyProject
Projects --> DeleteProject

Configuration --> ManageEnvVariables
Configuration --> ManageDomains
Configuration --> IntegrateWebHooks

ManageDomains --> CreateDomain
ManageDomains --> ModifyDomain
ManageDomains --> DeleteDomain

IntegrateWebHooks .> TestsUnit

Deploy --> TestsUnit
Deploy --> BuildApplication
Deploy --> DeployProduction

Deploy --> NotifyTeam : <<extends>>
Deploy --> DeploymentReports : <<extends>>

@enduml
