@startuml "Deployment app"

left to right direction

actor "Developer" as User

usecase "Deploy Project" as Deploy
usecase "Projects" as Projects

usecase "Configure Environments" as Configuration

rectangle "During Deployment" {
    usecase "Run Tests Unit" as TestsUnit
    usecase "Build Application" as BuildApplication
    usecase "Deploy to Production" as DeployProduction
}

usecase "Project (CRUD)" as ProjectCRUD

usecase "Domain names (CRUD)" as DomainsCRUD
usecase "Link domain to project" as DomainProject

usecase "Manage environments variables" as ManageEnvVariables
usecase "Manage domains names" as ManageDomains
usecase "Integrate Webhooks (automated deployment)" as IntegrateWebHooks

rectangle "After Deployment" {
    usecase "Notify Team on Deployment" as NotifyTeam
    usecase "Generate Deployment Reports" as DeploymentReports
}
User -- Deploy
User -- Configuration
User -- Projects

Projects -- Deploy
Projects -- ProjectCRUD
Projects . DomainProject

Configuration -- ManageEnvVariables
Configuration -- ManageDomains
Configuration -- IntegrateWebHooks

ManageEnvVariables . "During Deployment"

ManageDomains -- DomainsCRUD
ManageDomains -- DomainProject

IntegrateWebHooks . TestsUnit

Deploy -- TestsUnit
Deploy -- BuildApplication
Deploy -- DeployProduction

Deploy -- DeploymentReports : <<extends>>
Deploy -- NotifyTeam : <<extends>>

@enduml
