@startuml "Deployment app"

left to right direction

actor "Developer" as User

usecase "Deploy Project" as Deploy
usecase "Projects" as Projects

usecase "Configure Environments" as Configuration

rectangle "During Deployment" {
    usecase "Run Tests Unit" as TestsUnit
    usecase "Build Application" as BuildApplication
    usecase "Deploy to Production" as DeployProduction
}

usecase "Manage Project" as ProjectCRUD

usecase "Link domain to project" as DomainProject

usecase "Manage environments variables" as ManageEnvVariables
usecase "Domain names" as DomainNames
usecase "Manage domains names" as ManageDomains
usecase "Manage Webhooks (automated deployment)" as IntegrateWebHooks

rectangle "After Deployment" {
    usecase "Notify Team on Deployment" as NotifyTeam
    usecase "Generate Deployment Reports" as DeploymentReports
}
User -- Deploy
User -- Configuration
User -- Projects

Projects -- Deploy
Projects -- ProjectCRUD
Projects -- ManageEnvVariables
Projects . DomainProject

Configuration -- DomainNames
Configuration -- IntegrateWebHooks

ManageEnvVariables . "During Deployment" : <<includes>>

DomainNames -- ManageDomains
DomainNames -- DomainProject

IntegrateWebHooks . "During Deployment" : <<triggers>>

Deploy -- TestsUnit
Deploy -- BuildApplication
Deploy -- DeployProduction

Deploy -- DeploymentReports : <<extends>>
Deploy -- NotifyTeam : <<extends>>

@enduml
